CREATE TABLE IF NOT EXISTS chat_conversations (
    id varchar(36) PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    paper_id integer REFERENCES papers(id) ON DELETE SET NULL,
    title varchar(80) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS chat_conversations_user_updated_idx
    ON chat_conversations (user_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS chat_messages (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id varchar(36) NOT NULL
        REFERENCES chat_conversations(id) ON DELETE CASCADE,
    role varchar(16) NOT NULL CHECK (role IN ('user', 'assistant')),
    content text NOT NULL,
    sources json NOT NULL DEFAULT '[]'::json,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS chat_messages_conversation_created_idx
    ON chat_messages (conversation_id, created_at, id);
