import { useState } from "react";
import { Bot, FileText, Paperclip, Send, Sparkles } from "lucide-react";

const suggestions = ["Summarize this paper", "What are the key methods?", "Find the research gaps"];

function Chat() {
  const [message, setMessage] = useState("");
  const [messages, setMessages] = useState([]);
  function sendMessage(event) { event.preventDefault(); const trimmed = message.trim(); if (!trimmed) return; setMessages((current) => [...current, trimmed]); setMessage(""); }
  return <section className="flex h-[calc(100vh-64px)] min-h-0 flex-col px-4 sm:h-[calc(100vh-76px)] sm:px-8 lg:px-10"><div className="flex shrink-0 items-center gap-4 border-b border-[#e1e7ec] py-5"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[#e8f4f7] text-[#398798]"><Bot size={23} /></div><div><h1 className="text-xl font-bold text-[#173c5d] sm:text-2xl">Chat with your research</h1><p className="mt-1 text-xs text-[#788598] sm:text-sm">Ask questions grounded in your uploaded papers.</p></div></div><div className="min-h-0 flex-1 overflow-y-auto py-6 sm:py-8"><div className="mx-auto max-w-3xl">{messages.length === 0 ? <div className="pt-10 text-center sm:pt-16"><div className="mx-auto grid h-11 w-11 place-items-center rounded-full bg-[#eaf7f5] text-[#3b9995]"><FileText size={20} /></div><h2 className="mt-4 text-sm font-bold text-[#405369]">Start with a question</h2><p className="mx-auto mt-2 max-w-md text-xs leading-relaxed text-[#8997a6]">Ask about your uploaded papers. Your RAG-powered answers will appear here.</p><div className="mt-6 flex flex-wrap justify-center gap-2">{suggestions.map((item) => <button type="button" key={item} onClick={() => setMessage(item)} className="rounded-full border border-[#dbe5e9] bg-white px-3 py-2 text-[10px] text-[#536f7d] hover:bg-[#edf6fa]">{item}</button>)}</div></div> : <div className="space-y-5">{messages.map((item, index) => <div className="flex justify-end" key={`${item}-${index}`}><div className="max-w-[85%] rounded-2xl rounded-tr-sm bg-[#173c5d] px-4 py-3 text-sm text-white">{item}</div></div>)}</div>}</div></div><div className="shrink-0 border-t border-[#e1e7ec] bg-[#f6f8fa] py-4"><form className="mx-auto max-w-3xl" onSubmit={sendMessage}><div className="flex items-center gap-2 rounded-xl border border-[#dbe3e8] bg-white px-3 py-2 shadow-sm focus-within:border-[#64a9b0]"><button type="button" className="text-[#9aa7b6]" title="Attach paper"><Paperclip size={17} /></button><input className="min-w-0 flex-1 bg-transparent px-1 text-sm outline-none" value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Ask a question about your papers..." /><button type="submit" className="grid h-9 w-9 place-items-center rounded-lg bg-[#173c5d] text-white disabled:bg-[#b9c7cf]" disabled={!message.trim()} aria-label="Send message"><Send size={15} /></button></div><p className="mt-2 flex items-center justify-center gap-1 text-[10px] text-[#a0aab7]"><Sparkles size={12} /> AI response integration will connect here.</p></form></div></section>;
}
export default Chat;
